# 1.- La base de NumPy - ndarray

Toda la libería de NumPy se articula alrededor de una única estructura de datos: la **matriz multidimensional o ndarray (N-dimensional array)**.<br/>

**ndarray=matriz que puede tener distintas dimensiones**

# Características básicas de ndarray

Un ndarray puede contener **elementos de CUALQUIER TIPO**

**Todos los elementos** de un ndarray **deben tener EL MISMO TIPO**.
    
El **número de elementos se define en el momento de la creación y no puede modificarse** (bueno, exite el **método resize** que puede hacer incrementos automáticos aunque es bueno mantener en todo momento el control de la definición de los elementos originales.

Pero **la dimensión de la matriz sí puede modificarse (manteniendo el mismo número de elementos total)**


# Importación del módulo NumPy

Hay que recordar que **NumPy no es** un módulo **del core** de Python por lo que **SIEMPRE habrá que importarlo** de forma completa o componente a componente.

In [1]:
import numpy as np

# Creación de ndarrays

Existen **varias formas** de crear un ndarray en NumPy. Vamos a ver las más relevantes.

## Creación con una secuencia numérica

**Con un parámetro: np.arange(n)**

**Con dos parámetros: np.arange(n,m)**

**Con tres parámetros: np.arange(n,m,salto)**

In [5]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
print(array_secuencia_1)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2

array([5, 6, 7, 8, 9])

In [6]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

## Creación con una secuencia estática

**np.array(secuencia_estática)**

In [65]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
array_basico

array([1, 2, 3, 4, 5])

In [68]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Características que definen un ndarray

- **dtype**: **Tipo de dato de los elementos** del ndarray.

- **ndim**: Número de **dimensiones/ejes del ndarray**.

- **shape**: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones (**como dimensión matricial en álgebra**).

- **size**: **Número total de elementos** en el ndarray.

In [70]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
# Tipo de dato (único)
array.dtype

dtype('int32')

In [72]:
# Número de dimensiones
array.ndim

2

In [73]:
# Forma/Dimensiones
array.shape

(3, 4)

In [15]:
# Número total de elementos
array.size

12

# Operaciones aritméticas entre ndarrays y escalares

**El escalar opera con todos los elementos del ndarray**

In [74]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [77]:
# Suma
array + 5

In [79]:
# Resta
array - 2

array([4., 5., 6., 7., 8., 9.])

In [80]:
# Multiplicación
array * 3

array([18., 21., 24., 27., 30., 33.])

In [20]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [21]:
# División entera
array // 2

array([0., 1., 1., 2., 2., 3.])

In [81]:
# Potencia
array ** 2

array([ 36.,  49.,  64.,  81., 100., 121.])

# Operaciones aritméticas entre ndarrays

**Los dos ndarrays deben tener las mismas dimensiones y forma**.
(existe el **concepto de broadcasting** que, bajo ciertas circunstancias, puede modificar la dimensión de uno de los elementos para hacer congruente la operación. Sin embargo, como se comentaba en la definición del número de elementos de un ndarray, aquí también es aconsejable mantener el control de las dimensiones de las matrices para evitar posibles cálculos y resultados no deseados)

**La operación se aplica elemento a elemento.** 

In [82]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
array

array([1., 2., 3., 4., 5., 6.])

In [83]:
# Suma (elemento a elemento)
array + array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [25]:
# Resta (elemento a elmento)
array - array

array([0., 0., 0., 0., 0., 0.])

In [26]:
# Multiplicación (elemento a elmento)
array * array

array([ 1.,  4.,  9., 16., 25., 36.])

In [27]:
# División (elemento a elmento)
array / array

array([1., 1., 1., 1., 1., 1.])

In [84]:
# Suma de ndarrays de distinto tamaño
array1 = np.array([1, 2,3 ,4, 5])
array + array1

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

# Indexación

## Indexación en ndarrays unidimensionales

**array[a]** Se direcciona un **elemento**

**array[a:b]** Se direcciona un **segmento** del vector

**array[a:b:salto]** Se direcciona un **segmento** del vector ([a,b]) pero **con saltos** determinados por 'salto'

**array[:-b]** Se direcciona un **segmento** del vector en sentido inverso.

In [14]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
array[2]

3

In [86]:
# Indexación con primer parámetro
array[2]

3

In [16]:
# Indexación con primer y segundo parámetro
array[2:5]

array([3, 4, 5])

In [17]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [34]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Indexación en ndarrays multidimensionales

**Dos** posibles **formas** de realizar el acceso:<br/>

Mediante indexación **recursiva: array[a:b:c] [a:b:c]...[a:b:c]** en dim_1, dim_2, .....

Mediante indexación con **comas: array[a:b:c,a:b:c, ...a:b:c]** en dim_1, dim_2, ..... 


In [20]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array.shape

(4, 4)

In [95]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [96]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [97]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [98]:
# Indexación recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [99]:
# Indexación recursiva tercer nivel
array[1][0][3]

12

In [42]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [138]:
# Indexación con comas tercer nivel
array[1, 0, 3]

12

In [186]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [187]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

## Fancy indexing (con secuencias de enteros)

**array[[a,b,c]], a,b y c son referencias a la primera dimensión.**

**array[[a,b,c],[d,e,f]] a,b y c son referencias a la primera dimensión y d,e,f a la segunda.**


In [43]:
array = np.empty((8, 4))
for i in range(8):
    array[i] = i
array    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
array.shape

(8, 4)

In [145]:
# Indexación con un conjunto (arbitrario) de elementos
array[[2, 5]] # [2,5] es un set, en realidad estamos indexando primero array[2] y después array[5]


array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [146]:
# Indexación con un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [166]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]]  #Primera entrada seleciona fila y segunda entrada la columna dentro del vector (fila)

array([1., 5., 7., 2.])

# Modificación de un ndarray con slicing

Del mismo modo a como ocurre en Python básico, se puede utilizar la indexación/slicing para **modificar secciones del contenido de un ndarray**.

In [100]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
# Modificación de una posición
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [102]:
# Modificación de un slice
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

# Filtros

## Selección con filtros

In [25]:
datos = np.random.randn(4, 4) # Valores aleatorios según distribución normal estándar.
datos

array([[-0.15264091, -0.75238929, -1.07899257, -0.27672872],
       [ 0.36920706, -0.6719808 , -1.69503918,  1.05492124],
       [-0.2687582 , -0.77137453,  2.15069755,  0.83939848],
       [ 0.39667915,  1.45939545,  1.39637915,  0.99004709]])

In [113]:
# Filtro
datos[datos < 0]

array([-0.76224414, -0.03441471, -0.93504511, -0.22197348, -0.37248071,
       -0.30504016, -0.72331192])

In [114]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [115]:
personas[personas=='Miguel'] #Filtro

array(['Miguel', 'Miguel'], dtype='<U6')

## Modificación de matrices usando filtros

In [116]:
array = np.random.randn(7, 4)
array

array([[ 0.54721254, -0.07230828,  1.20026209, -0.98286506],
       [-1.06448152,  0.34426835,  1.03876949,  0.54047189],
       [-1.10777964,  1.65443438, -0.09885277, -0.17434943],
       [ 1.15731422, -0.39347113,  0.2385719 , -0.62610023],
       [-0.10618675,  0.37885613,  0.90985474, -0.61143734],
       [ 0.24828053,  0.01762653, -0.50550393,  3.37772329],
       [ 1.15041894, -0.96058114, -0.19354712,  0.57726611]])

In [117]:
# Eliminación de valores negativos mediante un filtro
array[array < 0] = 0 #Solo se asigna el valor cero a aquellos valores que cumplen el filtro.
array

array([[0.54721254, 0.        , 1.20026209, 0.        ],
       [0.        , 0.34426835, 1.03876949, 0.54047189],
       [0.        , 1.65443438, 0.        , 0.        ],
       [1.15731422, 0.        , 0.2385719 , 0.        ],
       [0.        , 0.37885613, 0.90985474, 0.        ],
       [0.24828053, 0.01762653, 0.        , 3.37772329],
       [1.15041894, 0.        , 0.        , 0.57726611]])

# Reshape

**La dimensión (shape) de los ndarrays se pueden modificar, aunque el número total de elementos permanece invariante**

In [27]:
array = np.arange(32)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [30]:
array=array.reshape((8, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Transposición 

In [122]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [123]:
# Modificación de ejes/dimensiones
array = array.reshape(3, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [124]:
array.shape

(3, 5)

In [129]:
# Trasposición de ejes/dimensiones"
array=array.T
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
array.shape

(3, 5)

# Axis (importante en aplicación de funciones)

Valor **0**: Aplicará la función **por columnas**


Valor **1**: Aplicará la función **por filas**

In [131]:
array.sum(axis=1)

array([10, 35, 60])

In [132]:
array.sum(axis=0)

array([15, 18, 21, 24, 27])