# 1.- La base de NumPy - ndarray

Toda la libería de NumPy se articula alrededor de una **única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array)**.<br/>

### Características básicas de ndarray

Un ndarray puede contener **elementos de CUALQUIER TIPO**

Todos los elementos de **un ndarray** deben tener **EL MISMO TIPO**.
    
El **tamaño de un ndarray** (número de elementos) **se define en** el momento de **la creación y no puede modificarse**.

Pero **la organización de esos elementos entre diferentes dimensiones sí puede modificarse**


### Uso básico de cualquier elemento de NumPy

Hay que recordar que **NumPy no es** un módulo **del core** de Python por lo que **SIEMPRE habrá que importarlo** de forma completa o componente a componente.

In [ ]:
import numpy as np

### Creación básica de ndarrays

Existen **varias formas** de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creación de un ndarray cuyos elementos son una secuencia numérica

In [146]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
array_secuencia_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2

array([5, 6, 7, 8, 9])

In [148]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#### Creación de un ndarray a partir de una secuencia básica de Python

In [151]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
array_basico

array([1, 2, 3, 4, 5])

In [152]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Consulta de la composición de un ndarray

- **dtype**: **Tipo de dato de los elementos** del ndarray.

- **ndim**: Número de **dimensiones/ejes del ndarray**.

- **shape**: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones (**como dimensión matricial en álgebra**).

- **size**: **Número total de elementos** en el ndarray.

In [153]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [154]:
# Tipo de dato (único)
array.dtype

dtype('int32')

In [156]:
# Número de dimensiones
array.ndim

2

In [155]:
# Forma/Dimensiones
array.shape

(3, 4)

In [157]:
# Número total de elementos
array.size

12

### Operaciones aritméticas entre ndarrays y escalares

In [158]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [159]:
# Suma
array + 5

array([ 6.,  7.,  8.,  9., 10., 11.])

In [160]:
# Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [161]:
# Multiplicación
array * 3

array([ 3.,  6.,  9., 12., 15., 18.])

In [162]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [163]:
# División entera
array // 2

array([0., 1., 1., 2., 2., 3.])

In [164]:
# Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [165]:
# Asignación con operador
array += 1
array

array([2., 3., 4., 5., 6., 7.])

### Operaciones aritméticas entre ndarrays

<b>IMPORTANTE:</b> <b>Los dos términos</b> de la operación tienen que ser ndarrays de las <b>mismas dimensiones y forma</b>. <b>Se aplica la operación elemento a elemento</b>.

In [166]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [167]:
# Suma (elemento a elemento)
array + array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [168]:
# Resta (elemento a elmento)
array - array

array([0., 0., 0., 0., 0., 0.])

In [169]:
# Multiplicación (elemento a elmento)
array * array

array([ 1.,  4.,  9., 16., 25., 36.])

In [170]:
# División (elemento a elmento)
array / array

array([1., 1., 1., 1., 1., 1.])

In [171]:
# Asignación con operador
array += array
array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [172]:
# Suma de ndarrays de distinto tamaño
array1 = np.array([1, 2,3 ,4, 5])
array + array1

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

### Indexación y slicing básico

En **ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python**. Es decir, se utiliza la indexación **[a:b:c]**.

In [174]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [175]:
# Indexación con primer parámetro
array[2]

3

In [176]:
# Indexación con primer y segundo parámetro
array[2:5]

array([3, 4, 5])

In [177]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [178]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

En **ndarrays multidimensionales**, existen **dos** posibles **formas** de realizar el acceso:<br/>
<ul>
<li>Mediante <b>indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li>Mediante <b>indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [179]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [180]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [181]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [182]:
# Indexación recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [183]:
# Indexación recursiva tercer nivel
array[1][0][3]

12

In [184]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [185]:
# Indexación con comas tercer nivel
array[1, 0, 3]

12

In [186]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [187]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

Del mismo modo a como ocurre en Python básico, se puede utilizar la indexación/slicing para **modificar secciones del contenido de un ndarray**.

In [189]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [190]:
# Modificación de una posición
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [191]:
# Modificación de un slice
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

### Indexación y slicing booleano

In [192]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [193]:
datos = np.random.randn(4, 4) # Valores aleatorios según distribución normal estándar.
datos

array([[ 0.39297946,  1.24226722,  0.02360426, -0.97697645],
       [-0.02118464,  0.93602282, -2.0183076 ,  2.85333486],
       [-0.11410864, -0.43686936,  0.3930954 ,  0.63183563],
       [ 0.21526818,  0.01785516, -0.16211002,  0.49503509]])

In [194]:
# Indexación/slicing booleano sobre valores
datos[datos < 0]

array([-0.97697645, -0.02118464, -2.0183076 , -0.11410864, -0.43686936,
       -0.16211002])

In [195]:
# Máscara booleana
personas == 'Miguel'

array([ True, False, False,  True])

In [196]:
# Indexación/slicing mediante máscara
datos[personas == 'Miguel']

array([[ 0.39297946,  1.24226722,  0.02360426, -0.97697645],
       [ 0.21526818,  0.01785516, -0.16211002,  0.49503509]])

In [197]:
# Indexación/slicing mediante máscara y básico combinado
datos[personas == 'Miguel', ::2]

array([[ 0.39297946,  0.02360426],
       [ 0.21526818, -0.16211002]])

In [198]:
# Indexación/slicing mediante máscara negativo por operador
datos[personas != 'Miguel']

array([[-0.02118464,  0.93602282, -2.0183076 ,  2.85333486],
       [-0.11410864, -0.43686936,  0.3930954 ,  0.63183563]])

In [199]:
# Indexación/slicing mediante máscara negativa por signo
datos[~(personas == 'Miguel')]

array([[-0.02118464,  0.93602282, -2.0183076 ,  2.85333486],
       [-0.11410864, -0.43686936,  0.3930954 ,  0.63183563]])

De nuevo, podemos utilizar indexación/slicing booleano para realizar **modificaciones sobre** el **contenido de un ndarray**.

In [200]:
array = np.random.randn(7, 4)
array

array([[ 0.41722618,  1.11085578, -0.41873079, -0.639918  ],
       [ 0.82259355, -0.93820341, -0.42460216, -1.38222057],
       [-0.82828463,  0.75338989,  0.22709018, -0.0919629 ],
       [-0.72732692,  1.16780315, -1.10469569,  2.01075484],
       [ 1.45646807, -1.11462791, -0.00324699,  0.49424165],
       [ 0.70327197, -1.20280775, -0.17328428, -0.22879771],
       [ 0.29688657, -0.20066531, -0.94401713,  1.68221828]])

In [201]:
# Eliminación de valores negativos mediante slicing
array[array < 0] = 0
array

array([[0.41722618, 1.11085578, 0.        , 0.        ],
       [0.82259355, 0.        , 0.        , 0.        ],
       [0.        , 0.75338989, 0.22709018, 0.        ],
       [0.        , 1.16780315, 0.        , 2.01075484],
       [1.45646807, 0.        , 0.        , 0.49424165],
       [0.70327197, 0.        , 0.        , 0.        ],
       [0.29688657, 0.        , 0.        , 1.68221828]])

### Indexación y slicing basado en secuencias de enteros - Fancy indexing

In [202]:
array = np.empty((8, 4))
for i in range(8):
    array[i] = i
array    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [220]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]]


array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [221]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

También podemos indexar de manera arbitraria en múltiples dimensiones, utilizando para ello, una secuencia de enteros por cada dimensión. El resultado será la combinación de secuencias.

In [222]:
array = np.arange(32)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [223]:
array=array.reshape((8, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [232]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]] 
#Primera entrada sleciona vector y segunda posición dentro del vector




array([ 4, 23, 29, 10])

### Trasposición y modificación de ejes/dimensiones

In [233]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [234]:
# Modificación de ejes/dimensiones
array2 = array.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [237]:
# Trasposición de ejes/dimensiones"
array=array2.T
array

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

**Axis**

Valor **0**: Aplicará la función **por columnas**


Valor **1**: Aplicará la función **por filas**

In [238]:
array.sum(axis=1)

array([15, 18, 21, 24, 27])

In [239]:
array.sum(axis=0)

array([10, 35, 60])