# 2.- Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de **funciones optimizadas** para aplicar sobre ndarrays de forma global **evitando** así la necesidad de utilizar **bucles (mucho más costosos)**.

In [2]:
import numpy as np

# Métodos de numpy

## Arange

In [3]:
np.arange(0,10) #Genera un array en forma de secuencia

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Zeros, ones

In [4]:
np.zeros(9) #Secuencia de ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,5)) #Matriz bidimensional

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(3) #secuencia

array([1., 1., 1.])

In [7]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

In [8]:

'''
secuencia en el intervalo [1,10]
secuencia con 5 elementos

'''
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## eye

In [9]:
np.eye(9)#matriz identidad de dimensión 9x9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Métodos de los arrays

## reshape

In [10]:
array=np.ones(6)
array

array([1., 1., 1., 1., 1., 1.])

In [11]:
array.reshape(3,2) #Reorganización en dimensión 3x2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas **"funciones universales"** (o ufuncs) que permiten la realización de **operaciones elemento a elemento de un array**. En función del número de parámetros encontramos **dos tipos de funciones universales**.

## Funciones unarias

Son aquellas funciones que reciben **como parámetro un único ndarray**.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada.</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [44]:
# Devuelve el valor absoluto de cada valor del ndarray
array = np.array([[1,-2,3,-4,0,1],[1,-2,0,3,-4,9]])
np.abs(array)

array([[1, 2, 3, 4, 0, 1],
       [1, 2, 0, 3, 4, 9]])

In [45]:
#Devuelve el sigo de cada elemento del ndarray (devuelve cero si el elemento es cero)
np.sign(array)

array([[ 1, -1,  1, -1,  0,  1],
       [ 1, -1,  0,  1, -1,  1]])

## Funciones binarias

Son aquellas funciones que reciben como **parámetro dos arrays**.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [46]:
array1 = np.random.randn(5, 5)
array1

array([[-0.40925291,  0.3490973 ,  0.29371747,  0.67550016,  1.4273018 ],
       [-0.33391442, -0.59206344, -1.41438665, -0.52270306, -0.00915054],
       [ 0.48387437, -1.16052439,  1.29192835, -0.61637893, -0.36165618],
       [ 0.31208819,  0.87006126, -0.29657875,  1.26492347,  0.95088172],
       [-1.41044047, -0.72893465,  1.31141735,  0.81685888,  1.67058562]])

In [47]:
array2 = np.random.randn(5, 5)
array2

array([[-0.01064447, -0.09248757, -1.39690382, -1.10051392,  1.49933658],
       [ 0.36168791,  0.47549657, -0.07170265, -0.1295734 , -0.29846311],
       [ 0.58808536,  1.39207254, -1.53351726, -0.75347655, -0.0946136 ],
       [-0.80323318,  0.95909064, -0.59066586, -0.1760554 , -0.09690176],
       [ 0.15214961, -1.28554953,  0.14420118, -0.80400924, -0.78167222]])

In [48]:
np.minimum(array1, array2)

array([[-0.40925291, -0.09248757, -1.39690382, -1.10051392,  1.4273018 ],
       [-0.33391442, -0.59206344, -1.41438665, -0.52270306, -0.29846311],
       [ 0.48387437, -1.16052439, -1.53351726, -0.75347655, -0.36165618],
       [-0.80323318,  0.87006126, -0.59066586, -0.1760554 , -0.09690176],
       [-1.41044047, -1.28554953,  0.14420118, -0.80400924, -0.78167222]])

In [49]:
np.divide(array1,array2)

array([[ 3.84474730e+01, -3.77453190e+00, -2.10263202e-01,
        -6.13804289e-01,  9.51955566e-01],
       [-9.23211453e-01, -1.24514766e+00,  1.97257244e+01,
         4.03403073e+00,  3.06588548e-02],
       [ 8.22796148e-01, -8.33666608e-01, -8.42460908e-01,
         8.18046597e-01,  3.82245462e+00],
       [-3.88539964e-01,  9.07173133e-01,  5.02109177e-01,
        -7.18480342e+00, -9.81284298e+00],
       [-9.27008918e+00,  5.67021833e-01,  9.09435921e+00,
        -1.01598196e+00, -2.13719458e+00]])

# Fusión condicional: np.where()

**np.where(condición, resultado si condición=True, resultado si else)**

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [50]:
array1 = np.random.randn(5, 5)
array1

array([[ 1.17285044e+00,  3.83383563e-01,  2.53063384e-01,
         8.99070671e-01, -5.19256902e-01],
       [-6.59144286e-01, -2.37148928e+00, -1.21775025e+00,
        -3.55919061e-01, -1.79115334e+00],
       [ 1.06699912e-01,  4.23138280e-03,  2.03684533e-03,
        -2.66817177e-01,  7.61430392e-01],
       [-9.33366179e-01, -4.34287865e-01, -2.80342476e-01,
         7.05207548e-01,  9.68284147e-01],
       [-6.34191653e-01, -3.54022265e-01, -9.37019324e-01,
        -3.09663362e-01, -2.48179904e+00]])

In [51]:
array2 = np.random.randn(5, 5)
array2

array([[-0.09713059, -0.63164927,  0.79255085,  1.51156886, -0.7205612 ],
       [-0.81090482,  0.83221191,  0.50439196,  0.29442102,  1.99829252],
       [-0.26517573, -0.18576005, -1.59612357,  1.65678014, -0.6728374 ],
       [-0.95259439,  1.80367818, -1.1550293 ,  0.15546937,  0.95347016],
       [ 1.52418406, -1.11694876, -0.8449127 ,  1.19441264, -0.39075262]])

In [52]:
array3=np.zeros((5,5))
array3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
# Fusión condicional
resultado=np.where(array1 < array2, array3, array2) 
'''
Si se cumple la condición array1<array2 el array resultante 
se rellena con la componente de array3. Si no se cumple se
rellena con la componente de array2.

'''
resultado

array([[-0.09713059, -0.63164927,  0.        ,  0.        , -0.7205612 ],
       [-0.81090482,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.26517573, -0.18576005, -1.59612357,  0.        , -0.6728374 ],
       [-0.95259439,  0.        , -1.1550293 ,  0.15546937,  0.95347016],
       [ 0.        , -1.11694876,  0.        ,  0.        ,  0.        ]])

# Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. <b>Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global</b> de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor <b>0</b>: Aplicará la función por <b>columnas</b></li>
<li>Valor <b>1</b>: Aplicará la función por <b>filas</b></li>

In [54]:
array = np.random.randn(5, 4)
array

array([[-0.75554984, -0.57395183,  0.76441553,  0.29041842],
       [ 0.89491192,  0.93324129, -0.85859445, -0.0955895 ],
       [ 0.16200701,  0.21534107,  1.293693  ,  0.60513901],
       [-0.25956269,  1.89512757,  0.2984584 ,  1.62206663],
       [ 0.70008182, -0.47480402, -0.08296952, -0.81381624]])

In [56]:
# Operación global
np.sum(array)

5.760063571615137

In [57]:
# Operación por columnas
np.sum(array, axis=0)

array([0.74188823, 1.99495408, 1.41500296, 1.60821831])

In [58]:
# Operación por filas
np.sum(array, axis=1)

array([-0.27466773,  0.87396926,  2.2761801 ,  3.55608991, -0.67150796])

Adicionalmente **algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos**. **En este caso** la sintáxis cambiará y se utilizará la notación "**ndarray.funcion()**" 

In [59]:
array.sum()

5.760063571615137

In [60]:
np.argmax(array)

13

In [61]:
np.argmin(array)

6

In [62]:
np.cumsum(array)

array([-0.75554984, -1.32950168, -0.56508615, -0.27466773,  0.62024419,
        1.55348547,  0.69489103,  0.59930153,  0.76130854,  0.97664961,
        2.27034262,  2.87548163,  2.61591894,  4.51104651,  4.80950491,
        6.43157153,  7.13165336,  6.65684934,  6.57387981,  5.76006357])

In [63]:
np.cumprod(array)

array([-7.55549842e-01,  4.33649218e-01,  3.31488196e-01,  9.62702770e-02,
        8.61534181e-02,  8.04019269e-02, -6.90326479e-02,  6.59879637e-03,
        1.06905129e-03,  2.30210653e-04,  2.97821911e-04,  1.80223656e-04,
       -4.67793363e-05, -8.86528098e-05, -2.64591756e-05, -4.29185457e-05,
       -3.00464938e-05,  1.42661960e-05, -1.18365950e-06,  9.63281327e-07])

# Operaciones sobre ndarrays booleanos

**Una condición booleana** aplicada sobre un ndarray **devuelve una máscara booleana**. **Sobre esa máscara se pueden aplicar funciones** que solo **afectarán a las posiciones con 'True'** en la máscara

**Son operaciones que se aplican directamente sobre las condiciones** (en realidad la condición devuelve un mapa booleano y la función se aplica sobre dicho mapa.)

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [64]:
array = np.random.randn(5, 5)
array

array([[ 0.11613547,  3.04550508, -1.57958475,  1.08308386, -0.62082727],
       [-2.86692519,  0.13133988, -1.19654971, -0.03709108,  0.38121351],
       [ 0.78903407, -2.70009458, -0.0085213 ,  0.12991905, -1.42523465],
       [ 1.44074319,  0.85986478,  0.11710333,  0.93260477, -0.87408863],
       [-0.11141341,  0.58276844,  1.45746439,  1.51460711, -1.31555062]])

In [65]:
array>0 # Esta condición aplicada sobre un array devuelve una máscara booleana

array([[ True,  True, False,  True, False],
       [False,  True, False, False,  True],
       [ True, False, False,  True, False],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True, False]])

In [66]:
# Elementos mayores que 0
(array > 0).sum()

14

In [67]:
# Elementos menores que la media
(array < array.mean()).sum()

11

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para <b>comprobar si alguno de los elementos es True</b>.</li>
<li><b>all:</b> Para <b>comprobar si todos los elementos son True</b>.</li>
</ul>

In [70]:
# Alguno de los elementos cumple la condición
(array == 0).any()

False

In [73]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

False

# Multiplicación matricial algebraica (arrays bi-dimensionales)

**Hasta ahora habíamos visto multiplicación de matrices elemento a elemento**

In [74]:
A=np.array([[1,2,3],[-1,2,4],[2,2,2]])
B=np.array([[1,1],[2,-3],[1,0]])
print(A)
print()
print(B)

[[ 1  2  3]
 [-1  2  4]
 [ 2  2  2]]

[[ 1  1]
 [ 2 -3]
 [ 1  0]]


In [75]:
print('Dimensión de A,B',A.shape,B.shape)

Dimensión de A,B (3, 3) (3, 2)


In [78]:
np.dot(A,B)

array([[ 8, -5],
       [ 7, -7],
       [ 8, -4]])

In [79]:
A*B 
'''
Da error porque sus dimensiones no son iguales y no se puede realizar
la operación elemento a elemento
'''

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

Recuerda que en **multiplicación de matrices en álgebra A*B, siendo (a,b) las dimensiones de A y (c,d) las dimensiones de B, se tiene que cumplir 
que b=c para que sean multiplicables.**

# Ordenación de ndarrays

In [80]:
array = np.random.randn(5, 5)
array

array([[-0.61628011,  0.92438458, -0.02298434,  0.73031417,  1.95067516],
       [ 0.1359884 ,  0.75845487,  0.07111865,  0.07170479, -0.44886825],
       [-0.0954842 ,  0.07354673,  2.57254508, -0.76841623, -1.79928446],
       [ 1.58516185,  1.69887395, -0.18090469,  1.12571815, -0.83289571],
       [ 1.8907355 ,  0.12183341, -0.6604252 , -1.06357589, -1.52610714]])

In [81]:
# Datos ordenados
np.sort(array) 


array([[-0.61628011, -0.02298434,  0.73031417,  0.92438458,  1.95067516],
       [-0.44886825,  0.07111865,  0.07170479,  0.1359884 ,  0.75845487],
       [-1.79928446, -0.76841623, -0.0954842 ,  0.07354673,  2.57254508],
       [-0.83289571, -0.18090469,  1.12571815,  1.58516185,  1.69887395],
       [-1.52610714, -1.06357589, -0.6604252 ,  0.12183341,  1.8907355 ]])

In [82]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

array([[-0.61628011,  0.07354673, -0.6604252 , -1.06357589, -1.79928446],
       [-0.0954842 ,  0.12183341, -0.18090469, -0.76841623, -1.52610714],
       [ 0.1359884 ,  0.75845487, -0.02298434,  0.07170479, -0.83289571],
       [ 1.58516185,  0.92438458,  0.07111865,  0.73031417, -0.44886825],
       [ 1.8907355 ,  1.69887395,  2.57254508,  1.12571815,  1.95067516]])

# Funciones de conjunto

NumPy permite realizar <b>tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto</b>.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arrays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [83]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [84]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [87]:
np.unique(array1) #Conjunto único de elementos no repetidos

array([0, 2, 3, 5, 6])

In [86]:
np.union1d(array1, array2) #Unión de dos vectores

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
np.in1d(array1, array2) #Devuelve si cada elemento del primer array está contenido en el segundo

array([ True, False, False, False,  True,  True,  True,  True])