# 2.- Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de **funciones optimizadas** para aplicar sobre ndarrays de forma global **evitando** así la necesidad de utilizar **bucles (mucho más costosos)**.

In [48]:
import numpy as np

# Métodos de numpy

## Arange

In [49]:
np.arange(0,10) #Genera un array en forma de secuencia

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Zeros, ones

In [50]:
np.zeros(9) #Secuencia de ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,5)) #Matriz bidimensional

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.ones(3) #secuencia

array([1., 1., 1.])

In [55]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

In [56]:

'''
secuencia en el intervalo [1,10]
secuencia con 5 elementos

'''
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## eye

In [57]:
np.eye(9)#matriz identidad de dimensión 9x9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Métodos de los arrays

## reshape

In [9]:
array=np.ones(6)
array

array([1., 1., 1., 1., 1., 1.])

In [10]:
array.reshape(3,2) #Reorganización en dimensión 3x2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas **"funciones universales"** (o ufuncs) que permiten la realización de **operaciones elemento a elemento de un array**. En función del número de parámetros encontramos **dos tipos de funciones universales**.

## Funciones unarias

Son aquellas funciones que reciben **como parámetro un único ndarray**.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada.</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [58]:
# Devuelve el valor absoluto de cada valor del ndarray
array = np.array([[1,-2,3,-4,0,1],[1,-2,0,3,-4,9]])
np.abs(array)

array([[1, 2, 3, 4, 0, 1],
       [1, 2, 0, 3, 4, 9]])

In [60]:
#Devuelve el sigo de cada elemento del ndarray (devuelve cero si el elemento es cero)
np.sign(array)

array([[ 1, -1,  1, -1,  0,  1],
       [ 1, -1,  0,  1, -1,  1]])

## Funciones binarias

Son aquellas funciones que reciben como **parámetro dos arrays**.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [61]:
array1 = np.random.randn(5, 5)
array1

array([[-1.18462296,  0.66609811,  0.42422033, -0.8493772 , -0.81628468],
       [-1.04751363, -2.09008824,  0.01278284,  0.12361773, -0.05232463],
       [-1.6661952 ,  1.90078177,  0.55653149, -0.52108732,  0.57780287],
       [-0.63841635, -0.23925559,  0.04108749,  0.94165485,  0.55666088],
       [-0.59370228, -0.59933899,  0.82506955, -0.51172795,  1.00906336]])

In [62]:
array2 = np.random.randn(5, 5)
array2

array([[-0.04966299, -0.24929186,  1.23937265,  0.29995557, -0.24555188],
       [ 0.49563681, -0.18925318, -0.60613309,  2.109226  , -0.03836775],
       [ 0.6498426 ,  0.74901589, -1.1634802 , -1.70974662, -1.43482877],
       [-0.04099829,  0.26060444, -1.40459234,  0.64803753, -1.13377703],
       [ 0.52735149,  0.33719821,  0.41161124,  0.28223986,  1.86779495]])

In [15]:
np.minimum(array1, array2)

array([[ 0.04294416,  0.52412502, -0.84308365, -1.90594524, -1.89094581],
       [ 0.04131088, -0.45347547, -0.3862531 ,  0.64523678, -1.01122609],
       [-0.61128141, -0.28548704, -0.50441988, -0.94013077, -1.12490763],
       [-2.10959813, -0.40647949, -0.46893699, -0.90286771, -0.27297372],
       [-0.58581454, -0.42491221, -1.55409915,  0.34564122, -1.34310145]])

In [63]:
np.divide(array1,array2)

array([[ 2.38532350e+01, -2.67196093e+00,  3.42286346e-01,
        -2.83167669e+00,  3.32428603e+00],
       [-2.11347022e+00,  1.10438741e+01, -2.10891567e-02,
         5.86080993e-02,  1.36376600e+00],
       [-2.56399809e+00,  2.53770554e+00, -4.78333441e-01,
         3.04774589e-01, -4.02698136e-01],
       [ 1.55717806e+01, -9.18079475e-01, -2.92522536e-02,
         1.45308690e+00, -4.90979143e-01],
       [-1.12581891e+00, -1.77740857e+00,  2.00448739e+00,
        -1.81309596e+00,  5.40243115e-01]])

# Fusión condicional: np.where()

**np.where(condición, resultado si condición=True, resultado si else)**

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [64]:
array1 = np.random.randn(5, 5)
array1

array([[ 0.89584721, -0.70646252,  1.46525196,  1.1749141 ,  0.61036857],
       [ 0.71552822, -0.17795004, -0.11285991,  0.95628815, -0.26724662],
       [ 1.50681286, -1.39451688, -0.83955512,  0.4897043 ,  1.14507766],
       [-0.94725196,  0.41315186,  0.78565279,  0.18930237,  0.66288282],
       [-2.20613745, -0.45177943, -0.20440565,  0.67737944,  1.43614566]])

In [65]:
array2 = np.random.randn(5, 5)
array2

array([[-0.45663681,  0.31123122, -0.90084513, -0.41975319,  0.27169354],
       [ 0.03776104, -2.49261298,  0.65751837,  1.1996606 , -0.16532164],
       [ 1.08019869, -0.79577974,  0.56266336,  1.40739441,  0.89525895],
       [-2.45824582, -0.3430442 , -1.52725594, -1.32883974,  0.70110754],
       [ 0.28177479, -1.67098933, -1.68956459,  0.83165544,  0.552424  ]])

In [66]:
# Fusión condicional
resultado=np.where(array1 < array2, 0, array2) 
'''
Si se cumple la condición array1<array2 el array resultante 
se rellena con la componente de array3. Si no se cumple se
rellena con la componente de array2.

'''
resultado

array([[-0.45663681,  0.        , -0.90084513, -0.41975319,  0.27169354],
       [ 0.03776104, -2.49261298,  0.        ,  0.        ,  0.        ],
       [ 1.08019869,  0.        ,  0.        ,  0.        ,  0.89525895],
       [-2.45824582, -0.3430442 , -1.52725594, -1.32883974,  0.        ],
       [ 0.        , -1.67098933, -1.68956459,  0.        ,  0.552424  ]])

# Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. <b>Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global</b> de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor <b>0</b>: Aplicará la función por <b>columnas</b></li>
<li>Valor <b>1</b>: Aplicará la función por <b>filas</b></li>

In [72]:
array = np.random.randn(5, 4)
array

array([[-1.5821799 , -0.80568418,  0.09787364,  0.0652732 ],
       [ 1.26049035,  0.980752  ,  0.45098607, -1.8787897 ],
       [-1.24655129, -0.16327797,  0.74328999, -1.15649617],
       [-0.54598301, -0.85651886, -1.66326694, -1.24934584],
       [ 1.09835742,  0.76917279, -1.0955382 ,  0.78168603]])

In [68]:
# Operación global
np.sum(array)

1.2265083741393439

In [69]:
# Operación por columnas
np.sum(array, axis=0)

array([-0.50734285,  2.87233843, -1.13112494, -0.00736226])

In [71]:
# Operación por filas
np.sum(array, axis=1)

array([-1.48352722,  2.70055822,  1.0291311 ,  0.24376339, -1.26341711])

Adicionalmente **algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos**. **En este caso** la sintáxis cambiará y se utilizará la notación "**ndarray.funcion()**" 

In [26]:
np.argmax(array)

9

In [27]:
np.argmin(array)

12

In [28]:
np.cumsum(array)

array([ 0.45837242, -0.24686214,  0.7247002 ,  1.44653866,  1.41185695,
        0.82959945,  0.55557547,  0.89512714,  1.73318575,  3.71850031,
        4.41434805,  3.92878591,  0.84319714,  0.17699587, -0.41904145,
       -0.37625532,  0.33147707, -0.20067382, -0.26497228,  0.16402316])

In [29]:
np.cumprod(array)

array([ 4.58372420e-01, -3.23260072e-01, -3.14067314e-01, -2.26705866e-01,
        7.86254738e-03, -4.57802716e-03,  1.25448926e-03,  4.25963925e-04,
        3.56982738e-04,  7.08723026e-04,  4.93163315e-04, -2.39461434e-04,
        7.38879513e-04, -4.92242468e-04,  2.93394881e-04,  1.25532328e-05,
        8.88432938e-06, -4.72780379e-06,  3.03990515e-07,  1.30410544e-07])

# Operaciones sobre ndarrays booleanos

**Una condición booleana** aplicada sobre un ndarray **devuelve una máscara booleana**. **Sobre esa máscara se pueden aplicar funciones** que solo **afectarán a las posiciones con 'True'** en la máscara

**Son operaciones que se aplican directamente sobre las condiciones** (en realidad la condición devuelve un mapa booleano y la función se aplica sobre dicho mapa.)

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [75]:
array = np.random.randn(5, 5)
array

array([[-0.29056106,  0.35164644,  2.23088928,  0.18895213, -0.21444718],
       [-0.15542383, -1.18483787, -0.70475449, -1.36539573, -1.32922437],
       [-0.42165872, -0.96267586,  0.36453573,  1.32625739,  0.37416221],
       [ 0.36456899, -0.51987591, -0.19780425,  0.86588271, -0.76767359],
       [ 0.52301536, -0.17925092,  1.26183807, -1.15522932,  0.79687925]])

In [76]:
array>0 # Esta condición aplicada sobre un array devuelve una máscara booleana

array([[False,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True, False, False,  True, False],
       [ True, False,  True, False,  True]])

In [77]:
# Elementos mayores que 0
(array > 0).sum()

11

In [33]:
# Elementos menores que la media
(array < array.mean()).sum()

13

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para <b>comprobar si alguno de los elementos es True</b>.</li>
<li><b>all:</b> Para <b>comprobar si todos los elementos son True</b>.</li>
</ul>

In [34]:
# Alguno de los elementos cumple la condición
(array == 0).any()

False

In [35]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

True

# Multiplicación matricial algebraica (arrays bi-dimensionales)

**Hasta ahora habíamos visto multiplicación de matrices elemento a elemento**

In [36]:
A=np.array([[1,2,3],[-1,2,4],[2,2,2]])
B=np.array([[1,1],[2,-3],[1,0]])
print(A)
print()
print(B)

[[ 1  2  3]
 [-1  2  4]
 [ 2  2  2]]

[[ 1  1]
 [ 2 -3]
 [ 1  0]]


In [37]:
print('Dimensión de A,B',A.shape,B.shape)

Dimensión de A,B (3, 3) (3, 2)


In [38]:
np.dot(A,B)

array([[ 8, -5],
       [ 7, -7],
       [ 8, -4]])

In [39]:
A*B 
'''
Da error porque sus dimensiones no son iguales y no se puede realizar
la operación elemento a elemento
'''

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

Recuerda que en **multiplicación de matrices en álgebra A*B, siendo (a,b) las dimensiones de A y (c,d) las dimensiones de B, se tiene que cumplir 
que b=c para que sean multiplicables.**

# Ordenación de ndarrays

In [78]:
array = np.random.randn(5, 5)
array

array([[ 0.73129354, -0.62462886,  0.42992598, -0.96352587,  0.41894123],
       [ 0.32853884, -0.22525715, -0.62471842,  1.29351575, -0.78910127],
       [-1.18224041,  0.87595022, -0.81835235,  0.06177426, -1.67897309],
       [-0.51107518,  0.19750327,  0.01282485,  0.36012451, -1.24910842],
       [-0.66417552, -0.27121165,  0.07905091, -1.32254354, -2.28775057]])

In [79]:
# Datos ordenados
np.sort(array) 


array([[-0.96352587, -0.62462886,  0.41894123,  0.42992598,  0.73129354],
       [-0.78910127, -0.62471842, -0.22525715,  0.32853884,  1.29351575],
       [-1.67897309, -1.18224041, -0.81835235,  0.06177426,  0.87595022],
       [-1.24910842, -0.51107518,  0.01282485,  0.19750327,  0.36012451],
       [-2.28775057, -1.32254354, -0.66417552, -0.27121165,  0.07905091]])

In [81]:
# Datos ordenados según el primer eje
np.sort(array, axis=1)

array([[-0.96352587, -0.62462886,  0.41894123,  0.42992598,  0.73129354],
       [-0.78910127, -0.62471842, -0.22525715,  0.32853884,  1.29351575],
       [-1.67897309, -1.18224041, -0.81835235,  0.06177426,  0.87595022],
       [-1.24910842, -0.51107518,  0.01282485,  0.19750327,  0.36012451],
       [-2.28775057, -1.32254354, -0.66417552, -0.27121165,  0.07905091]])

# Funciones de conjunto

NumPy permite realizar <b>tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto</b>.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arrays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [43]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [44]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [45]:
np.unique(array1) #Conjunto único de elementos no repetidos

array([0, 2, 3, 5, 6])

In [46]:
np.union1d(array1, array2) #Unión de dos vectores

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
np.in1d(array1, array2) #Devuelve si cada elemento del primer array está contenido en el segundo

array([ True, False, False, False,  True,  True,  True,  True])