# 3.- Álgebra lineal

Hasta el momento **hemos visto cómo aplicar funciones "elemento a elemento"** a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de **tratamientos/operaciones matriciales**. Todas estas funciones están **disponibles a través del submódulo linalg**.

In [8]:
import numpy as np
import numpy.linalg as linalg

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [3]:
array1 = np.random.randn(3, 3)
array1

array([[ 0.01720639,  1.32902437, -0.93969007],
       [-0.12777034, -1.43386349, -1.68289612],
       [-0.10982299,  0.16902438,  1.80097989]])

In [4]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.dot(array, array) #Calculamos el producto algebraico de matrices


array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [6]:
linalg.inv(array1) #Cálculo de la inversa de la matriz array1

array([[-3.3783604 , -3.75247625, -5.2691535 ],
       [ 0.61002922, -0.10616414,  0.21908916],
       [-0.26326304, -0.21886076,  0.21338073]])

In [7]:
linalg.solve(array1,array)#Resuelve la ecuación Ax = B, siendo aquí A=array1, B=array y x el resultado de esta operación

array([[-42.87234975, -55.27233991, -67.67233006],
       [  0.99604255,   1.71899679,   2.44195103],
       [  0.62370209,   0.35495901,   0.08621593]])