# 3.- Álgebra lineal

Hasta el momento **hemos visto cómo aplicar funciones "elemento a elemento"** a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de **tratamientos/operaciones matriciales**. Todas estas funciones están **disponibles a través del submódulo linalg**.

In [9]:
import numpy as np
import numpy.linalg as linalg

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [15]:
array1 = np.random.randn(3, 3)
array1

array([[-0.87454481, -0.2391419 ,  0.21022257],
       [ 0.9293051 ,  0.90645286, -0.19681328],
       [-0.3883811 , -0.24403015,  0.22965294]])

In [16]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.dot(array, array) #Calculamos el producto algebraico de matrices


array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [18]:
linalg.inv(array1) #Cálculo de la inversa de la matriz array1

array([[-1.97806573, -0.04470187,  1.77239684],
       [ 1.6919672 ,  1.47230179, -0.28704687],
       [-1.54734501,  1.4888756 ,  7.04679562]])

In [19]:
linalg.solve(array1,array)#Resuelve la ecuación Ax = B, siendo aquí A=array1, B=array y x el resultado de esta operación

array([[10.5002754 , 10.24990464,  9.99953388],
       [ 2.69462416,  5.57184628,  8.44906841],
       [46.74740048, 53.73572668, 60.72405288]])