# 4.- Generación de números aleatorios

In [13]:
import numpy as np

## rand
Genera números aleatorios sobre una **distribución uniforme en el intervalo** ``[0, 1)``.

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(4,4)

In [ ]:
[a,b] #distr. uniforme
a+(b-a)*alet

## randn
Genera números aletororios según una **distribución normal estándar**.

In [ ]:
np.random.randn(4)

In [ ]:
np.random.randn(4,5)

## randint
Genera **enteros aleatorios dentro de un intervalo especificado**

In [14]:
np.random.randint(1,7,100) # 100 enteros aleatorios en el intervalo [1,7]

array([4, 4, 5, 1, 2, 2, 5, 6, 2, 2, 4, 5, 3, 5, 6, 5, 4, 5, 3, 3, 6, 2,
       6, 4, 3, 1, 4, 4, 1, 4, 2, 1, 2, 4, 3, 3, 4, 2, 4, 2, 6, 4, 6, 3,
       3, 4, 6, 5, 1, 2, 5, 6, 2, 1, 4, 2, 6, 6, 1, 6, 3, 3, 2, 5, 6, 1,
       4, 2, 5, 4, 1, 1, 3, 5, 5, 5, 5, 2, 2, 5, 3, 4, 6, 3, 4, 3, 2, 4,
       6, 3, 3, 2, 4, 2, 5, 3, 6, 6, 3, 6])

In [ ]:
np.random.randint(1,3,(3,7)) # matriz 3x7 con números aleatorios en el intervalo [1,3]

## normal
Genera números aleatorios según una **distribución normal con media y desviación estándar especificada**.

In [15]:
# Normal Dist
# Mean of 1, std of 0.1, 10 elements
np.random.normal(1, 0.1, 10)

array([1.08233942, 0.82952834, 0.89226802, 0.98991531, 1.02283582,
       1.03804324, 1.12693755, 0.99085893, 0.89751257, 0.96164763])

In [ ]:
np.random.normal(1,0.1,(2,2))

## Otras distribuciones

In [16]:
dir(np.random)

['Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_pickle',
 'absolute_import',
 'beta',
 'binomial',
 'bit_generator',
 'bounded_integers',
 'bytes',
 'chisquare',
 'choice',
 'common',
 'default_rng',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'generator',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mt19937',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'pcg64',
 'permutation',
 'philox',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'sfc64',
 'shuffle',
 'standard_cauchy',
 'st

In [17]:
help(np.random.poisson)

Help on built-in function poisson:

poisson(...) method of numpy.random.mtrand.RandomState instance
    poisson(lam=1.0, size=None)
    
    Draw samples from a Poisson distribution.
    
    The Poisson distribution is the limit of the binomial distribution
    for large N.
    
    Parameters
    ----------
    lam : float or array_like of floats
        Expectation of interval, must be >= 0. A sequence of expectation
        intervals must be broadcastable over the requested size.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``lam`` is a scalar. Otherwise,
        ``np.array(lam).size`` samples are drawn.
    
    Returns
    -------
    out : ndarray or scalar
        Drawn samples from the parameterized Poisson distribution.
    
    Notes
    -----
    The Poisson distribution
    
    .. math:: f(k; \l

In [19]:
np.random.poisson(7,(2,5))

array([[ 7,  5,  9, 10,  6],
       [12,  1,  4,  8,  4]])