# NumPy - Ejercicios

### 1. Crea una matriz 3x3 con valores entre 0 y 8.

In [1]:
import numpy as np
np.random.randint(0,8,(3,3))

array([[2, 0, 2],
       [6, 1, 7],
       [2, 4, 1]])

### 2. Crea una matriz 5x5 con valores enteros aleatorios tomados del intervalo [1,4] debajo de la diagonal principal.

In [3]:
a=np.random.randint(1,10,(5,5))
print(a)
print()

for cont_line in range(0,5):
    for cont_element in range(0,5):
        if cont_element < cont_line:
            a[cont_line][cont_element]=np.random.randint(1,4)
a

[[7 7 2 3 1]
 [3 8 4 5 3]
 [2 3 2 6 8]
 [4 3 3 9 3]
 [6 2 5 6 7]]



array([[7, 7, 2, 3, 1],
       [1, 8, 4, 5, 3],
       [1, 1, 2, 6, 8],
       [1, 3, 2, 9, 3],
       [3, 3, 1, 1, 7]])

### 3. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 1 y el resto valgan n.

In [16]:
def myfunction(n):
    import numpy as np
    a=np.eye(n)
    a[(a!=1)]=n
    return a
    
myfunction(5)

array([[1., 5., 5., 5., 5.],
       [5., 1., 5., 5., 5.],
       [5., 5., 1., 5., 5.],
       [5., 5., 5., 1., 5.],
       [5., 5., 5., 5., 1.]])

### 4. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [20]:
def myfunction(n,m,mode):
    a=np.arange(n*m)
    a=a.reshape(n,m)
    if mode==False:
        return a
    else:
        return a.T
myfunction(3,4,True)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 5. Crea una función que reciba dos arrays y genere un array que contenga 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array y cero en los restantes.

In [22]:
def myfunction(array1,array2):
    output=np.where(array1>array2,1,0)
    return output
a=np.random.randn(10)
b=np.random.rand(10)
print(a)
print(b)

myfunction(a,b)

[ 1.56287277 -0.69619906  0.46287828 -0.27915612  1.92701008  0.91251172
  0.03548853  0.22380408 -0.43607131 -0.24207272]
[0.79977043 0.03696898 0.69259083 0.40593123 0.96787283 0.04443821
 0.27123325 0.69626185 0.80797732 0.72691717]


array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0])

### 6. Crea una función que reciba un array unidimensional y una secuencia de enteros y devuelva el vector resultante de seleccionar los índices de la secuencia aplicados desde el final.

In [5]:
def myfunction(array,secuencia):
    a=array[-secuencia]
    return a
array=np.random.randn(20)
print(array)
secuencia=np.random.randint(1,10,10)
print(secuencia)
myfunction(array,secuencia)

[-1.00147412  0.43109391 -1.21264091 -0.2401453   0.9703491   1.14052691
 -0.85155215  1.29096855 -0.73406535 -0.21825549  1.83844989  0.28714193
  0.40149889  0.73930547 -0.34587398 -0.02836102 -0.33306292  0.49892778
 -0.39390106  0.24016439]
[4 4 3 5 8 7 7 6 8 7]


array([-0.33306292, -0.33306292,  0.49892778, -0.02836102,  0.40149889,
        0.73930547,  0.73930547, -0.34587398,  0.40149889,  0.73930547])

### 7. Replica la función del ejercicio 5 utilizando la función np.where

### 8. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [30]:
def myfunction(A):
    result=(A<0).any()
    return result
A=np.random.randn(4,5)
print(A)
print()
myfunction(A)

[[-0.02639877  0.69013709  0.22336443 -0.66450008  0.60548774]
 [ 0.44833994  0.55789729  0.9507533  -0.41474896 -0.9972932 ]
 [ 0.57976098 -0.00679214  0.90465561  0.59675791 -0.45456171]
 [-0.87138052 -0.27794613 -0.32144489 -0.00737497 -0.95736239]]



True

### 9. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [34]:
def myfunction(A):
    result=(A<0).any()
    if result==False:
        output='No hay negativos'
    else:
        negativos=A[A<0]
        result=np.abs(negativos)
        
    return result
A=np.random.randn(4,5)
print(A)
print()
myfunction(A)

[[-0.59008106  1.74308721 -0.04488745 -0.21442836 -0.03925026]
 [ 1.01271336 -1.56616472 -0.68530788 -0.17376377  1.49477736]
 [ 0.6430581   1.06179345  1.33312962 -0.00358292  0.30644946]
 [ 1.03320657 -1.19018582  1.47592618 -0.03986219  0.1758527 ]]



array([0.59008106, 0.04488745, 0.21442836, 0.03925026, 1.56616472,
       0.68530788, 0.17376377, 0.00358292, 1.19018582, 0.03986219])

### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [48]:
def myfunction(A,B):
    result=np.union1d(A,B)
    print(result)
    result=np.unique(result)
    result=result.sort()
    return result
A=np.random.randint(1,100,(4,5))
print(A)
B=np.random.randint(1,100,(4,5))
print()
print(B)
print()
myfunction(A,B)


[[96 26 10 91 14]
 [54  3 13 26 68]
 [ 4 92  4 27 55]
 [ 6 99 31 99 76]]

[[84 25 23 60 78]
 [93 61 79 14 63]
 [19 84 47 46 78]
 [72 73 25  3 31]]

[ 3  4  6 10 13 14 19 23 25 26 27 31 46 47 54 55 60 61 63 68 72 73 76 78
 79 84 91 92 93 96 99]


### 11. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [81]:
def myfunction(names,B,name):
    index=np.where(names==name)[0]
    B=B.T
    vector=B[index]
    print(vector)
    print()
    minimo=np.max(vector)
    maximo=np.min(vector)
    media=np.mean(vector)
    mediana=np.median(vector)
    std=np.std(vector)
    output=(minimo,maximo,media,mediana,std)
    return output
names=np.array(['juan','pedro','mariano','luisa','carmen'])
array=np.random.randn(10,len(names))
print(array)
print()
myfunction(names,array,"pedro")

[[ 1.44534572 -0.92754018 -1.24572665  0.8593534   1.25789457]
 [-0.65058583  0.50817027  0.86956467  0.02476583 -0.15947658]
 [-0.84143605 -0.09475077  1.20552827 -0.1489976  -0.09595698]
 [ 0.08508409  2.02475181 -0.11720077  0.94557177  0.04896203]
 [-1.31580587 -1.06868345  0.86180307  1.88784624  0.71961468]
 [ 0.08828723 -1.72482138  0.08001813 -0.57519201 -1.17743428]
 [-0.53222135 -1.16104209 -0.47726054 -0.43757702  0.29787127]
 [ 0.15920452  0.94322585  1.11432413 -0.10696156 -0.53542323]
 [-0.77741887  0.12292268  1.07524035  0.48474586  0.4238805 ]
 [-0.60695626 -1.10532515  0.5048834  -0.6773914   1.62520537]]

[[-0.92754018  0.50817027 -0.09475077  2.02475181 -1.06868345 -1.72482138
  -1.16104209  0.94322585  0.12292268 -1.10532515]]



(2.024751810734958,
 -1.7248213775440087,
 -0.2483092406501827,
 -0.511145476668956,
 1.104637095761563)

In [69]:

import numpy as np

# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
arr=['pedro','pepe']
result = np.where(arr == 'pedro')


print('Tuple of arrays returned : ', result)
print("Elements with value 19 exists at following indices", result[0], sep='\n')

Tuple of arrays returned :  (array([], dtype=int64),)
Elements with value 19 exists at following indices
[]


In [72]:
import numpy as np
array = np.array(['A', 'D', 'A', 'A', 'A', 'D', 'A', 'A', 'D', 'A'])
print(np.where(array == 'D'))


(array([1, 5, 8], dtype=int64),)
