# Pandas - Ejercicios (I)

### 1. Crea un función que reciba un número entero n y genere una serie de tamaño n cuyos valores sean una secuencia numérica de múltiplos de cinco ascendentes y su índice sea una secuencia numérica de múltiplos de cinco en orden inverso.

In [15]:
def myfunction(n):
    import pandas as pd
    valores=[]
    for cont in range(0,n):
        valores.append((cont+1)*5)
    indices=valores[::-1]
    serie=pd.Series(valores,index=indices)
    return serie

myfunction(4)

20     5
15    10
10    15
5     20
dtype: int64

### 2. Crea una función que reciba una lista de palabras y devuelva un DataFrame en el que las filas sean las palabras y en columnas tenga la longitud de la palaba y su frecuencia en la lista.

In [19]:
def myfunction(word_list):
    import pandas as pd
    longitud=[]
    frecuencia=[]
    for word in word_list:
        cadena=str(word)
        longitud.append(len(cadena))
        frecuencia.append(word_list.count(word)/len(word_list)*100)
    datos={'longitud':longitud,'frecuencia':frecuencia}
    df=pd.DataFrame(datos,index=word_list)
    return df

lista=['perro','gato','gallina','gallina','búfalo']
myfunction(lista)

longitud  frecuencia
perro           5        20.0
gato            4        20.0
gallina         7        40.0
gallina         7        40.0
búfalo          6        20.0

### 3. Crea una función que reciba un DataFrame cualquiera y genere otro cuyas dimensiones sean las del recibido traspuestas y su contenido sean números positivos aleatorios generados con una distribución normal.

In [32]:
import numpy as np
def myfunction(df):
    import pandas as pd
    import numpy as np
    df_t=df.T
    print()
    print('Esta es la matriz traspuesta')
    print(df_t)
    size=np.size(df_t)
    dimension=np.shape(df_t)
    
    valores=np.random.randn(size)
    valores=np.abs(valores)
    matriz=valores.reshape(dimension)
    print()
    print('Esta es la nueva matriz antes de convertirla en dataframe')
    print(matriz)
    df_out=pd.DataFrame(matriz)
    return df_out

entrada=np.random.randn(2,3)
print(entrada)
myfunction(entrada)

[[-2.20030513  1.24153761  0.67436529]
 [-1.37881022  0.94286032 -0.49196358]]

Esta es la matriz traspuesta
[[-2.20030513 -1.37881022]
 [ 1.24153761  0.94286032]
 [ 0.67436529 -0.49196358]]

Esta es la nueva matriz antes de convertirla en dataframe
[[0.81951411 1.05663584]
 [0.7148344  1.13961066]
 [0.25235987 0.70914634]]


0         1
0  0.819514  1.056636
1  0.714834  1.139611
2  0.252360  0.709146

### 4. Crea una función que reciba una ndarray bidimensional y devuelva un DataFrame creado a partir del array recibido. Crea otra función que reciba un DataFrame y establezca como índice de filas la secuencia 'f1'...'fn' y como índice de columnas la secuencia 'c1'...'cm'. Utiliza ambas funciones de forma conjunta para obtener un DataFrame de 4x8 relleno con valores aleatorios generados con una distribución normal.

In [46]:
import numpy as np
import pandas as pd
def to_df(ndarray):
    import pandas as pd
    import numpy as np
    df=pd.DataFrame(ndarray)
    return df
def add_index(df):
    dimensiones=df.shape
    filas=dimensiones[0]
    columnas=dimensiones[1]
    index_filas=[]
    index_columnas=[]
    for cont in range(0,filas):
        index_filas.append('f'+str(cont+1))
    for cont in range(0,columnas):
        index_columnas.append('c'+str(cont+1))
    df.columns=index_columnas
    df.index=index_filas
    return df
n=4
m=8
array=np.random.randn(n,m)
print(array)
print()
df=to_df(array)
add_index(df)

[[-0.299906   -1.81390477  0.32232525  0.62123436 -1.01704232 -0.53189471
  -2.95161699 -0.13120221]
 [-0.26027261 -1.20904596 -0.39952748  1.22474384  0.27022743  0.16241571
  -0.26208902 -1.86992545]
 [ 0.53450215 -0.87866988  0.30747748  2.2164152   1.71087217 -1.01717901
  -1.71299377 -1.03006418]
 [-0.1840075   0.72986087 -0.03369246  1.72774667  1.89450457 -0.47520243
   0.50826107 -0.15300504]]



c1        c2        c3        c4        c5        c6        c7  \
f1 -0.299906 -1.813905  0.322325  0.621234 -1.017042 -0.531895 -2.951617   
f2 -0.260273 -1.209046 -0.399527  1.224744  0.270227  0.162416 -0.262089   
f3  0.534502 -0.878670  0.307477  2.216415  1.710872 -1.017179 -1.712994   
f4 -0.184007  0.729861 -0.033692  1.727747  1.894505 -0.475202  0.508261   

          c8  
f1 -0.131202  
f2 -1.869925  
f3 -1.030064  
f4 -0.153005